import type { Metadata } from "next";
import "./globals.css";
import {Poppins} from 'next/font/google'

const brand = Poppins({weight:["300","400","600","700","800"], subsets:['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={brand.className}
      >
        {children}
      </body>
    </html>
  );
}
